#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $FORUM_DB_USER WITH PASSWORD '$FORUM_DB_PASSWORD';
    CREATE DATABASE forum;
    GRANT ALL PRIVILEGES ON DATABASE forum TO $FORUM_DB_USER;
EOSQL