"""empty message

Revision ID: 31dffef5e3e2
Revises: 7d614959f085
Create Date: 2021-02-15 01:18:03.712272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31dffef5e3e2'
down_revision = '7d614959f085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'deleted')
    # ### end Alembic commands ###
